In [49]:
import pandas as pd

In [50]:
df = pd.read_csv('Crops_data.csv')

In [51]:
df.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,2010,14,Chhattisgarh,Durg,777.92,1319.18,1695.77,46.12,45.87,...,256.96,0.00,0.00,0.00,2.00,32.29,34.30,0.11,0.49,0.15
1,1,2011,14,Chhattisgarh,Durg,806.55,1416.48,1756.23,44.98,50.19,...,506.02,0.08,0.02,250.00,0.00,0.00,0.00,0.12,0.54,0.00
2,1,2012,14,Chhattisgarh,Durg,807.07,1534.22,1900.97,43.87,47.69,...,252.98,0.13,0.02,153.85,1.99,33.70,35.69,0.12,0.54,1.32
3,1,2013,14,Chhattisgarh,Durg,819.44,1296.24,1581.86,41.54,43.33,...,237.45,0.05,0.01,200.00,1.90,32.83,34.74,0.11,0.50,0.77
4,1,2014,14,Chhattisgarh,Durg,834.87,1444.24,1729.89,44.25,50.96,...,602.17,0.05,0.02,400.00,0.00,0.00,0.00,0.33,0.51,0.00

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 80 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Dist Code                                    2484 non-null   int64
 1   Year                                         2484 non-null   int64
 2   State Code                                   2484 non-null   int64
 3   State Name                                   2484 non-null   str
 4   Dist Name                                    2484 non-null   str
 5   RICE AREA (1000 ha)                          2484 non-null   float64
 6   RICE PRODUCTION (1000 tons)                  2484 non-null   float64
 7   RICE YIELD (Kg per ha)                       2484 non-null   float64
 8   WHEAT AREA (1000 ha)                         2484 non-null   float64
 9   WHEAT PRODUCTION (1000 tons)                 2484 non-null   float64
 10  WHEAT YIELD (Kg per ha)                      2484 non-null   float64
 11  KHARIF SORGHUM AREA (1000 ha)                2484 non-null   float64
 12  KHARIF SORGHUM PRODUCTION (1000 tons)        2484 non-null   float64
 13  KHARIF SORGHUM YIELD (Kg per ha)             2484 non-null   float64
 14  RABI SORGHUM AREA (1000 ha)                  2484 non-null   float64
 15  RABI SORGHUM PRODUCTION (1000 tons)          2484 non-null   float64
 16  RABI SORGHUM YIELD (Kg per ha)               2484 non-null   float64
 17  SORGHUM AREA (1000 ha)                       2484 non-null   float64
 18  SORGHUM PRODUCTION (1000 tons)               2484 non-null   float64
 19  SORGHUM YIELD (Kg per ha)                    2484 non-null   float64
 20  PEARL MILLET AREA (1000 ha)                  2484 non-null   float64
 21  PEARL MILLET PRODUCTION (1000 tons)          2484 non-null   float64
 22  PEARL MILLET YIELD (Kg per ha)               2484 non-null   float64
 23  MAIZE AREA (1000 ha)                         2484 non-null   float64
 24  MAIZE PRODUCTION (1000 tons)                 2484 non-null   float64
 25  MAIZE YIELD (Kg per ha)                      2484 non-null   float64
 26  FINGER MILLET AREA (1000 ha)                 2484 non-null   float64
 27  FINGER MILLET PRODUCTION (1000 tons)         2484 non-null   float64
 28  FINGER MILLET YIELD (Kg per ha)              2484 non-null   float64
 29  BARLEY AREA (1000 ha)                        2484 non-null   float64
 30  BARLEY PRODUCTION (1000 tons)                2484 non-null   float64
 31  BARLEY YIELD (Kg per ha)                     2484 non-null   float64
 32  CHICKPEA AREA (1000 ha)                      2484 non-null   float64
 33  CHICKPEA PRODUCTION (1000 tons)              2484 non-null   float64
 34  CHICKPEA YIELD (Kg per ha)                   2484 non-null   float64
 35  PIGEONPEA AREA (1000 ha)                     2484 non-null   float64
 36  PIGEONPEA PRODUCTION (1000 tons)             2484 non-null   float64
 37  PIGEONPEA YIELD (Kg per ha)                  2484 non-null   float64
 38  MINOR PULSES AREA (1000 ha)                  2484 non-null   float64
 39  MINOR PULSES PRODUCTION (1000 tons)          2484 non-null   float64
 40  MINOR PULSES YIELD (Kg per ha)               2484 non-null   float64
 41  GROUNDNUT AREA (1000 ha)                     2484 non-null   float64
 42  GROUNDNUT PRODUCTION (1000 tons)             2484 non-null   float64
 43  GROUNDNUT YIELD (Kg per ha)                  2484 non-null   float64
 44  SESAMUM AREA (1000 ha)                       2484 non-null   float64
 45  SESAMUM PRODUCTION (1000 tons)               2484 non-null   float64
 46  SESAMUM YIELD (Kg per ha)                    2484 non-null   float64
 47  RAPESEED AND MUSTARD AREA (1000 ha)          2484 non-null   float64
 48  RAPESEED AND MUSTARD PRODUCTION (1000 tons)  2484 non-null   float64
 49  RAPESEED AND MUSTARD YIELD (Kg per ha)       2484 non-null   float64
 50  SAFFLOWER AREA (1000 ha)                     2484 non-null   float64
 51  SAFFLOWER PRODUCTION (1000 tons)             2484 non-null   float64
 52  SAFFLOWER YIELD (Kg per ha)                  2484 non-null   float64
 53  CASTOR AREA (1000 ha)                        2484 non-null   float64
 54  CASTOR PRODUCTION (1000 tons)                2484 non-null   float64
 55  CASTOR YIELD (Kg per ha)                     2484 non-null   float64
 56  LINSEED AREA (1000 ha)                       2484 non-null   float64
 57  LINSEED PRODUCTION (1000 tons)               2484 non-null   float64
 58  LINSEED YIELD (Kg per ha)                    2484 non-null   float64
 59  SUNFLOWER AREA (1000 ha)                     2484 non-null   float64
 60  SUNFLOWER PRODUCTION (1000 tons)             2484 non-null   float64
 61  SUNFLOWER YIELD (Kg per ha)                  2484 non-null   float64
 62  SOYABEAN AREA (1000 ha)                      2484 non-null   float64
 63  SOYABEAN PRODUCTION (1000 tons)              2484 non-null   float64
 64  SOYABEAN YIELD (Kg per ha)                   2484 non-null   float64
 65  OILSEEDS AREA (1000 ha)                      2484 non-null   float64
 66  OILSEEDS PRODUCTION (1000 tons)              2484 non-null   float64
 67  OILSEEDS YIELD (Kg per ha)                   2484 non-null   float64
 68  SUGARCANE AREA (1000 ha)                     2484 non-null   float64
 69  SUGARCANE PRODUCTION (1000 tons)             2484 non-null   float64
 70  SUGARCANE YIELD (Kg per ha)                  2484 non-null   float64
 71  COTTON AREA (1000 ha)                        2484 non-null   float64
 72  COTTON PRODUCTION (1000 tons)                2484 non-null   float64
 73  COTTON YIELD (Kg per ha)                     2484 non-null   float64
 74  FRUITS AREA (1000 ha)                        2484 non-null   float64
 75  VEGETABLES AREA (1000 ha)                    2484 non-null   float64
 76  FRUITS AND VEGETABLES AREA (1000 ha)         2484 non-null   float64
 77  POTATOES AREA (1000 ha)                      2484 non-null   float64
 78  ONION AREA (1000 ha)                         2484 non-null   float64
 79  FODDER AREA (1000 ha)                        2484 non-null   float64
dtypes: float64(75), int64(3), str(2)
memory usage: 1.5 MB

In [52]:
df['State Name'].unique()

<StringArray>
[    'Chhattisgarh',   'Madhya Pradesh',   'Andhra Pradesh',
        'Telangana',        'Karnataka',       'Tamil Nadu',
      'Maharashtra',          'Gujarat',        'Rajasthan',
           'Punjab',          'Haryana',    'Uttar Pradesh',
      'Uttarakhand',            'Assam', 'Himachal Pradesh',
           'Kerala',           'Orissa',      'West Bengal',
            'Bihar',        'Jharkhand']
Length: 20, dtype: str

Data set Contains Crops Data for 20 indian States

In [53]:
df['Year'].unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017])

Data for 8 years from 2010 to 2017

In [54]:
import re

cols = df.columns

crop_columns = [col for col in cols if re.search(r'AREA',col)]
len(crop_columns)
crop_names = [re.search(r'^(.*?)\s*AREA', col).group(1) for col in crop_columns]
df.columns

Index(['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name',
       'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)',
       'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)',
       'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)',
       'KHARIF SORGHUM AREA (1000 ha)',
       'KHARIF SORGHUM PRODUCTION (1000 tons)',
       'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)',
       'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)',
       'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)',
       'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)',
       'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)',
       'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)',
       'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)',
       'FINGER MILLET PRODUCTION (1000 tons)',
       'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)',
       'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)',
       'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)',
       'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)',
       'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)',
       'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)',
       'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)',
       'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)',
       'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)',
       'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 tons)',
       'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)',
       'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)',
       'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)',
       'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)',
       'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)',
       'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)',
       'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)',
       'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)',
       'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)',
       'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)',
       'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)',
       'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)',
       'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)',
       'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)',
       'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)',
       'FODDER AREA (1000 ha)'],
      dtype='str')

Keeping only high value crops

In [61]:
high_value_crops = [
    'RICE',
    'WHEAT',
    'GROUNDNUT',
    'SESAMUM',
    'RAPESEED AND MUSTARD',
    'SUNFLOWER',
    'SAFFLOWER',
    'SOYABEAN',
    'OILSEEDS',
    'SUGARCANE',
    'COTTON',
]

base_cols = [
    'Dist Code',
    'Year',
    'State Code',
    'State Name',
    'Dist Name'
]

crop_cols = [
    col for col in df.columns
    if any(crop in col for crop in high_value_crops)
]

ndf = df[base_cols+crop_cols]

In [62]:
ndf

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SOYABEAN YIELD (Kg per ha),OILSEEDS AREA (1000 ha),OILSEEDS PRODUCTION (1000 tons),OILSEEDS YIELD (Kg per ha),SUGARCANE AREA (1000 ha),SUGARCANE PRODUCTION (1000 tons),SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha)
0,1,2010,14,Chhattisgarh,Durg,777.92,1319.18,1695.77,46.12,45.87,...,1148.66,114.35,112.83,986.66,4.42,1.13,256.96,0.00,0.00,0.00
1,1,2011,14,Chhattisgarh,Durg,806.55,1416.48,1756.23,44.98,50.19,...,802.03,106.25,78.18,735.80,4.07,2.06,506.02,0.08,0.02,250.00
2,1,2012,14,Chhattisgarh,Durg,807.07,1534.22,1900.97,43.87,47.69,...,1194.76,104.27,109.66,1051.69,4.97,1.26,252.98,0.13,0.02,153.85
3,1,2013,14,Chhattisgarh,Durg,819.44,1296.24,1581.86,41.54,43.33,...,1003.99,108.22,99.31,917.64,3.94,0.93,237.45,0.05,0.01,200.00
4,1,2014,14,Chhattisgarh,Durg,834.87,1444.24,1729.89,44.25,50.96,...,465.22,99.93,46.20,462.30,5.75,3.46,602.17,0.05,0.02,400.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,1.33,1.58,1187.97,0.00,0.00,0.00,0.00,0.00,0.00
2480,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,1.27,0.84,661.42,0.00,0.00,0.00,0.00,0.00,0.00
2481,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,1.42,0.95,669.01,0.00,0.00,0.00,0.00,0.00,0.00
2482,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2483,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,645.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [63]:
ndf.isnull().sum()

Dist Code                                      0
Year                                           0
State Code                                     0
State Name                                     0
Dist Name                                      0
RICE AREA (1000 ha)                            0
RICE PRODUCTION (1000 tons)                    0
RICE YIELD (Kg per ha)                         0
WHEAT AREA (1000 ha)                           0
WHEAT PRODUCTION (1000 tons)                   0
WHEAT YIELD (Kg per ha)                        0
GROUNDNUT AREA (1000 ha)                       0
GROUNDNUT PRODUCTION (1000 tons)               0
GROUNDNUT YIELD (Kg per ha)                    0
SESAMUM AREA (1000 ha)                         0
SESAMUM PRODUCTION (1000 tons)                 0
SESAMUM YIELD (Kg per ha)                      0
RAPESEED AND MUSTARD AREA (1000 ha)            0
RAPESEED AND MUSTARD PRODUCTION (1000 tons)    0
RAPESEED AND MUSTARD YIELD (Kg per ha)         0
SAFFLOWER AREA (1000 ha)                       0
SAFFLOWER PRODUCTION (1000 tons)               0
SAFFLOWER YIELD (Kg per ha)                    0
SUNFLOWER AREA (1000 ha)                       0
SUNFLOWER PRODUCTION (1000 tons)               0
SUNFLOWER YIELD (Kg per ha)                    0
SOYABEAN AREA (1000 ha)                        0
SOYABEAN PRODUCTION (1000 tons)                0
SOYABEAN YIELD (Kg per ha)                     0
OILSEEDS AREA (1000 ha)                        0
OILSEEDS PRODUCTION (1000 tons)                0
OILSEEDS YIELD (Kg per ha)                     0
SUGARCANE AREA (1000 ha)                       0
SUGARCANE PRODUCTION (1000 tons)               0
SUGARCANE YIELD (Kg per ha)                    0
COTTON AREA (1000 ha)                          0
COTTON PRODUCTION (1000 tons)                  0
COTTON YIELD (Kg per ha)                       0
dtype: int64

In [64]:
zero_counts = (ndf == 0).sum()
total_len = len(ndf)
zero_df = pd.DataFrame(zero_counts)
zero_df['total_len'] = total_len
zero_df.rename(columns={
    0:"Count of 0"
},inplace=True)

In [65]:
zero_df['Percentage of 0 values'] = ((zero_df['Count of 0']/zero_df['total_len']) * 100).round(2)
zero_df

,Count of 0,total_len,Percentage of 0 values
Dist Code,0,2484,0.00
Year,0,2484,0.00
State Code,0,2484,0.00
State Name,0,2484,0.00
Dist Name,0,2484,0.00
RICE AREA (1000 ha),233,2484,9.38
RICE PRODUCTION (1000 tons),241,2484,9.70
RICE YIELD (Kg per ha),236,2484,9.50
WHEAT AREA (1000 ha),384,2484,15.46
WHEAT PRODUCTION (1000 tons),391,2484,15.74
WHEAT YIELD (Kg per ha),380,2484,15.30
GROUNDNUT AREA (1000 ha),608,2484,24.48
GROUNDNUT PRODUCTION (1000 tons),610,2484,24.56
GROUNDNUT YIELD (Kg per ha),597,2484,24.03
SESAMUM AREA (1000 ha),327,2484,13.16
SESAMUM PRODUCTION (1000 tons),427,2484,17.19
SESAMUM YIELD (Kg per ha),395,2484,15.90
RAPESEED AND MUSTARD AREA (1000 ha),572,2484,23.03
RAPESEED AND MUSTARD PRODUCTION (1000 tons),610,2484,24.56
RAPESEED AND MUSTARD YIELD (Kg per ha),591,2484,23.79
SAFFLOWER AREA (1000 ha),2071,2484,83.37
SAFFLOWER PRODUCTION (1000 tons),2099,2484,84.50
SAFFLOWER YIELD (Kg per ha),2084,2484,83.90
SUNFLOWER AREA (1000 ha),1393,2484,56.08
SUNFLOWER PRODUCTION (1000 tons),1420,2484,57.17
SUNFLOWER YIELD (Kg per ha),1401,2484,56.40
SOYABEAN AREA (1000 ha),1434,2484,57.73
SOYABEAN PRODUCTION (1000 tons),1451,2484,58.41
SOYABEAN YIELD (Kg per ha),1412,2484,56.84
OILSEEDS AREA (1000 ha),863,2484,34.74
OILSEEDS PRODUCTION (1000 tons),965,2484,38.85
OILSEEDS YIELD (Kg per ha),969,2484,39.01
SUGARCANE AREA (1000 ha),535,2484,21.54
SUGARCANE PRODUCTION (1000 tons),486,2484,19.57
SUGARCANE YIELD (Kg per ha),523,2484,21.05
COTTON AREA (1000 ha),1254,2484,50.48
COTTON PRODUCTION (1000 tons),1361,2484,54.79
COTTON YIELD (Kg per ha),1320,2484,53.14

In [67]:
ndf.to_csv('filtered_crops.csv',index=False)