In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('rainfall_data.csv')

In [18]:
df.head(
)

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JF,MAM,JJAS,OND
0,Andaman & Nicobar Islands,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,Andaman & Nicobar Islands,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,Andaman & Nicobar Islands,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,Andaman & Nicobar Islands,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,Andaman & Nicobar Islands,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [4]:
df['SUBDIVISION'].unique()

<StringArray>
[         'Andaman & Nicobar Islands',                  'Arunachal Pradesh',
                  'Assam & Meghalaya',             'Naga Mani Mizo Tripura',
 'Sub Himalayan West Bengal & Sikkim',               'Gangetic West Bengal',
                             'Orissa',                          'Jharkhand',
                              'Bihar',                 'East Uttar Pradesh',
                 'West Uttar Pradesh',                        'Uttarakhand',
         'Haryana Delhi & Chandigarh',                             'Punjab',
                   'Himachal Pradesh',                    'Jammu & Kashmir',
                     'West Rajasthan',                     'East Rajasthan',
                'West Madhya Pradesh',                'East Madhya Pradesh',
                     'Gujarat Region',                 'Saurashtra & Kutch',
                       'Konkan & Goa',                 'Madhya Maharashtra',
                         'Matathwada',                           'Vidarbha',
                       'Chhattisgarh',             'Coastal Andhra Pradesh',
                          'Telangana',                         'Rayalseema',
                         'Tamil Nadu',                  'Coastal Karnataka',
           'North Interior Karnataka',           'South Interior Karnataka',
                             'Kerala',                        'Lakshadweep']
Length: 36, dtype: str

In [5]:
df['YEAR'].unique

<bound method Series.unique of 0       1901
1       1902
2       1903
3       1904
4       1905
        ...
4183    2013
4184    2014
4185    2015
4186    2016
4187    2017
Name: YEAR, Length: 4188, dtype: int64>

In [7]:
state_mapping = {
    'Chhattisgarh': ['Chhattisgarh'],
    
    'Madhya Pradesh': [
        'West Madhya Pradesh',
        'East Madhya Pradesh'
    ],
    
    'Andhra Pradesh': [
        'Coastal Andhra Pradesh',
        'Rayalseema'
    ],
    
    'Telangana': ['Telangana'],
    
    'Karnataka': [
        'Coastal Karnataka',
        'North Interior Karnataka',
        'South Interior Karnataka'
    ],
    
    'Tamil Nadu': ['Tamil Nadu'],
    
    'Maharashtra': [
        'Konkan & Goa',
        'Madhya Maharashtra',
        'Matathwada',
        'Vidarbha'
    ],
    
    'Gujarat': [
        'Gujarat Region',
        'Saurashtra & Kutch'
    ],
    
    'Rajasthan': [
        'West Rajasthan',
        'East Rajasthan'
    ],
    
    'Punjab': ['Punjab'],
    
    'Haryana': [
        'Haryana Delhi & Chandigarh'
    ],
    
    'Uttar Pradesh': [
        'East Uttar Pradesh',
        'West Uttar Pradesh'
    ],
    
    'Uttarakhand': ['Uttarakhand'],
    
    'Assam': [
        'Assam & Meghalaya'
    ],
    
    'Himachal Pradesh': [
        'Himachal Pradesh'
    ],
    
    'Kerala': ['Kerala'],
    
    'Orissa': ['Orissa'],
    
    'West Bengal': [
        'Sub Himalayan West Bengal & Sikkim',
        'Gangetic West Bengal'
    ],
    
    'Bihar': ['Bihar'],
    
    'Jharkhand': ['Jharkhand']
}

In [8]:
target_subdivisions = [
    subdivision
    for sublist in state_mapping.values()
    for subdivision in sublist
]

In [9]:
target_subdivisions

['Chhattisgarh',
 'West Madhya Pradesh',
 'East Madhya Pradesh',
 'Coastal Andhra Pradesh',
 'Rayalseema',
 'Telangana',
 'Coastal Karnataka',
 'North Interior Karnataka',
 'South Interior Karnataka',
 'Tamil Nadu',
 'Konkan & Goa',
 'Madhya Maharashtra',
 'Matathwada',
 'Vidarbha',
 'Gujarat Region',
 'Saurashtra & Kutch',
 'West Rajasthan',
 'East Rajasthan',
 'Punjab',
 'Haryana Delhi & Chandigarh',
 'East Uttar Pradesh',
 'West Uttar Pradesh',
 'Uttarakhand',
 'Assam & Meghalaya',
 'Himachal Pradesh',
 'Kerala',
 'Orissa',
 'Sub Himalayan West Bengal & Sikkim',
 'Gangetic West Bengal',
 'Bihar',
 'Jharkhand']

In [10]:
filtered_rainfall_df = df[
    (df['SUBDIVISION'].isin(target_subdivisions)) &
    (df['YEAR'].between(2010, 2017))
]

In [11]:
filtered_rainfall_df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JF,MAM,JJAS,OND
320,Assam & Meghalaya,2010,0.5,3.1,99.6,389.3,393.4,569.7,415.1,387.0,318.3,116.2,11.6,7.6,2711.5,3.7,882.3,1690.2,135.3
321,Assam & Meghalaya,2011,11.1,11.4,109.0,92.1,238.3,316.0,395.8,302.6,221.6,30.2,11.9,3.5,1743.4,22.5,439.4,1236.0,45.6
322,Assam & Meghalaya,2012,15.2,6.9,28.8,279.1,185.8,729.7,444.3,289.2,411.6,199.4,17.1,2.3,2609.4,22.1,493.7,1874.8,218.8
323,Assam & Meghalaya,2013,1.1,9.6,44.0,112.8,346.7,286.2,367.8,289.7,229.3,126.3,1.0,2.0,1816.4,10.7,503.5,1172.9,129.3
324,Assam & Meghalaya,2014,2.0,28.3,29.3,51.5,351.1,426.4,374.4,484.6,420.2,35.0,3.0,0.4,2206.1,30.3,431.9,1705.5,38.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4067,Kerala,2013,3.9,40.1,49.9,49.3,119.3,1042.7,830.2,369.7,318.6,259.9,154.9,17.0,3255.4,43.9,218.5,2561.2,431.8
4068,Kerala,2014,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,14.9,364.5,2164.8,502.1
4069,Kerala,2015,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,8.9,465.9,1514.7,611.1
4070,Kerala,2016,3.0,16.4,22.4,33.3,258.4,595.7,441.5,231.0,84.1,105.1,57.9,22.0,1870.9,19.3,314.2,1352.3,185.0
4071,Kerala,2017,12.7,0.3,87.8,52.8,213.3,579.8,378.5,462.6,435.5,228.0,152.1,61.4,2664.9,13.0,353.9,1856.5,441.5

In [12]:
reverse_mapping = {}

for state, subdivisions in state_mapping.items():
    for subdivision in subdivisions:
        reverse_mapping[subdivision] = state

filtered_rainfall_df['State_Name'] = (
    filtered_rainfall_df['SUBDIVISION']
    .map(reverse_mapping)
)

In [15]:
filtered_rainfall_df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JF,MAM,JJAS,OND,State_Name
320,Assam & Meghalaya,2010,0.5,3.1,99.6,389.3,393.4,569.7,415.1,387.0,318.3,116.2,11.6,7.6,2711.5,3.7,882.3,1690.2,135.3,Assam
321,Assam & Meghalaya,2011,11.1,11.4,109.0,92.1,238.3,316.0,395.8,302.6,221.6,30.2,11.9,3.5,1743.4,22.5,439.4,1236.0,45.6,Assam
322,Assam & Meghalaya,2012,15.2,6.9,28.8,279.1,185.8,729.7,444.3,289.2,411.6,199.4,17.1,2.3,2609.4,22.1,493.7,1874.8,218.8,Assam
323,Assam & Meghalaya,2013,1.1,9.6,44.0,112.8,346.7,286.2,367.8,289.7,229.3,126.3,1.0,2.0,1816.4,10.7,503.5,1172.9,129.3,Assam
324,Assam & Meghalaya,2014,2.0,28.3,29.3,51.5,351.1,426.4,374.4,484.6,420.2,35.0,3.0,0.4,2206.1,30.3,431.9,1705.5,38.5,Assam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4067,Kerala,2013,3.9,40.1,49.9,49.3,119.3,1042.7,830.2,369.7,318.6,259.9,154.9,17.0,3255.4,43.9,218.5,2561.2,431.8,Kerala
4068,Kerala,2014,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,14.9,364.5,2164.8,502.1,Kerala
4069,Kerala,2015,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,8.9,465.9,1514.7,611.1,Kerala
4070,Kerala,2016,3.0,16.4,22.4,33.3,258.4,595.7,441.5,231.0,84.1,105.1,57.9,22.0,1870.9,19.3,314.2,1352.3,185.0,Kerala
4071,Kerala,2017,12.7,0.3,87.8,52.8,213.3,579.8,378.5,462.6,435.5,228.0,152.1,61.4,2664.9,13.0,353.9,1856.5,441.5,Kerala

In [16]:
filtered_rainfall_df.to_csv('filtered_rainfall.csv',index=False)